name: streamlit_dashboard
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyarrow
  - pandas
  - pyyaml
  - snowflake-snowpark-python
  - altair>=4.0.0
  - pip
  - pip:
    - "snowflake-connector-python[secure-local-storage,pandas]"
    - snowflake
    - streamlit
    - watchdog
